# Site settings
title: 老王的自留地
email: wxtbeyond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这里是老王的自留地，一切都是老王和媳妇老张说了算，爱写啥写啥，也不打算开放评论，就这样吧。
url: "http://ivo-blog.tk" # the base hostname & protocol for your site
github_username:  ivo-wang

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: http://ivo-blog.tk



